# Generated by Django 2.2.7 on 2019-12-03 16:55

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='logo',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_text',
            field=wagtail.core.fields.RichTextField(help_text='Write an introduction for the Landing Page'),
        ),
    ]
