# Generated by Django 2.2.9 on 2020-04-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('base', '0006_auto_20191223_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursePage',
        ),
    ]
