# Generated by Django 2.2.7 on 2019-12-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191204_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'ordering': ['date_published']},
        ),
    ]
