# Generated by Django 2.2.7 on 2019-12-09 20:07

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191207_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='image_data',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Information about the header image, to appear after the article', null=True),
        ),
    ]
