# Generated by Django 2.2.7 on 2019-12-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpage_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
    ]
