# Generated by Django 2.2.8 on 2019-12-23 10:47

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191223_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='introduction',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtailmarkdown.fields.MarkdownField(blank=True),
        ),
    ]
