# Generated by Django 3.0.5 on 2020-07-30 17:16

from django.db import migrations
import pftl.blog.blocks
import wagtail.core.fields
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpage_extended_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='extended_body',
            field=wagtail.core.fields.StreamField([('content', wagtailmarkdown.blocks.MarkdownBlock(template='blog/markdown_block.html')), ('newsletter', pftl.blog.blocks.NewsletterSubscribe()), ('book', pftl.blog.blocks.BookInline())], null=True),
        ),
    ]
