# delete all compiled and cached files generated by python in this directory

find . -path "*/*.pyc"  -delete
find . -path "*/*.pyo"  -delete
find . -path "*/__pycache__" -type d -exec rm -r {} ';'

rsync -avz --delete * pftl@digital:~/pftl/