# Generated by Django 2.2.7 on 2019-11-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpagegalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Post Date'),
        ),
    ]
