#!/bin/bash

NAME="PFTL"                                    		# Name of the application
DJANGODIR=/webapps/pftl/pftl/                 		# Django project directory
SOCKFILE=/webapps/pftl/run/gunicorn.sock       		# we will communicte using this unix socket
USER=pftl		                                # the user to run as
GROUP=webapps                                           # the group to run as
NUM_WORKERS=2                                           # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=pftl.settings.production    	# which settings file should Django use
DJANGO_WSGI_MODULE=pftl.wsgi                   # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source /webapps/pftl/venv/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec /webapps/pftl/venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=/webapps/pftl/logs/gunicorn.log