# Generated by Django 2.2.8 on 2019-12-17 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email_verified', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('secret_code', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreeChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_sent', models.DateTimeField(null=True)),
                ('ip_request', models.GenericIPAddressField(null=True)),
                ('ip_confirmation', models.GenericIPAddressField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='free_chapter.People')),
            ],
        ),
    ]
